# Generated by Django 4.0.3 on 2022-04-01 09:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_payment_id_alter_payment_pay1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='posts',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_path),
        ),
    ]
