# Generated by Django 4.0.3 on 2022-04-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_post_title_alter_post_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='f1',
        ),
    ]
