# Generated by Django 4.0.3 on 2022-03-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='link',
        ),
        migrations.AddField(
            model_name='courses',
            name='desc',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='courses',
            name='sid',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
