# Generated by Django 4.0.3 on 2022-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courses_id_remove_courses_link_courses_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('sid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('desc', models.CharField(default=None, max_length=400)),
                ('price', models.IntegerField(default=None)),
            ],
        ),
    ]
