# Generated by Django 4.0.3 on 2022-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_cart_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boughtcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('desc', models.CharField(default=None, max_length=400)),
                ('price', models.IntegerField(default=None)),
            ],
        ),
    ]
