# Generated by Django 4.0.3 on 2022-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_boughtcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
